import type { ComponentType, SVGProps } from "react";

// --- UI / conceptual icons (lucide) -----------------------------------------
import {
  Activity,
  Antenna,
  Aperture,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  AudioWaveform,
  Award,
  BadgeCheck,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarRange,
  Captions,
  ChartLine,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDollarSign,
  Clock,
  Cloud,
  CodeXml,
  Command,
  Compass,
  Container,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  Download,
  Ear,
  ExternalLink,
  Eye,
  FileKey,
  FileText,
  FlaskConical,
  FolderKanban,
  Gauge,
  Gem,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  HeartPulse,
  House,
  Inbox,
  Infinity as InfinityIcon,
  KeyRound,
  Layers,
  LayoutGrid,
  Lightbulb,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Microscope,
  Milestone,
  MousePointerClick,
  Network,
  Orbit,
  Phone,
  Play,
  Plug,
  Quote,
  Radar,
  Radio,
  Repeat,
  Rocket,
  Route,
  Router,
  Scale,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Server,
  ShieldAlert,
  ShieldCheck,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Soup,
  Sparkles,
  Split,
  SquareTerminal,
  Star,
  Stethoscope,
  Target,
  Terminal,
  Timer,
  TrendingUp,
  Trophy,
  User,
  Volume2,
  Waypoints,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";

// --- Brand marks ------------------------------------------------------------
// lucide dropped brand glyphs in v1, so brands come from react-icons. Only the
// marks actually referenced are imported so the icon barrels stay tree-shaken.
import { FaAws, FaLinkedinIn } from "react-icons/fa6";
import { RiOpenaiFill } from "react-icons/ri";
import {
  SiAnthropic,
  SiCelery,
  SiCurl,
  SiDjango,
  SiDocker,
  SiElasticsearch,
  SiFastapi,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGmail,
  SiGunicorn,
  SiHuggingface,
  SiJsonwebtokens,
  SiKubernetes,
  SiLangchain,
  SiLanggraph,
  SiLinux,
  SiLivekit,
  SiMongodb,
  SiNginx,
  SiPostgresql,
  SiPython,
  SiRedis,
  SiScikitlearn,
  SiScrapy,
  SiSelenium,
  SiSqlite,
  SiWebrtc,
  SiWhatsapp,
} from "react-icons/si";

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

/** Named lucide glyphs referenced from the data layer by string. */
const lucideRegistry = {
  Activity,
  Antenna,
  Aperture,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  AudioWaveform,
  Award,
  BadgeCheck,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarRange,
  Captions,
  ChartLine,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDollarSign,
  Clock,
  Cloud,
  CodeXml,
  Command,
  Compass,
  Container,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  Download,
  Ear,
  ExternalLink,
  Eye,
  FileKey,
  FileText,
  FlaskConical,
  FolderKanban,
  Gauge,
  Gem,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  HeartPulse,
  House,
  Inbox,
  Infinity: InfinityIcon,
  KeyRound,
  Layers,
  LayoutGrid,
  Lightbulb,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  Microscope,
  Milestone,
  MousePointerClick,
  Network,
  Orbit,
  Phone,
  Play,
  Plug,
  Quote,
  Radar,
  Radio,
  Repeat,
  Rocket,
  Route,
  Router,
  Scale,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Server,
  ShieldAlert,
  ShieldCheck,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Soup,
  Sparkles,
  Split,
  SquareTerminal,
  Star,
  Stethoscope,
  Target,
  Terminal,
  Timer,
  TrendingUp,
  Trophy,
  User,
  Volume2,
  Waypoints,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
} satisfies Record<string, IconComponent>;

export type IconName = keyof typeof lucideRegistry;

/**
 * Resolve a data-layer icon string. Falls back to a neutral glyph rather than
 * crashing a section because one entry has a typo.
 */
export const brandIcons = {
  GitHub: SiGithub,
  LinkedIn: FaLinkedinIn,
  WhatsApp: SiWhatsapp,
  Gmail: SiGmail,
} satisfies Record<string, IconComponent>;

export function Icon({
  name,
  className,
  ...props
}: { name: string; className?: string } & SVGProps<SVGSVGElement>) {
  const Cmp =
    (lucideRegistry as Record<string, IconComponent>)[name] ??
    (brandIcons as Record<string, IconComponent>)[name] ??
    Circle;
  return <Cmp className={className} aria-hidden {...props} />;
}

type TechMeta = { label: string; Cmp: IconComponent; color: string };

/**
 * Technology marks keyed by the slug used in the data layer, each paired with
 * its brand colour. Icons render monochrome and adopt the brand colour on hover
 * — colour as a reward for interaction, not as decoration.
 */
export const techRegistry: Record<string, TechMeta> = {
  python: { label: "Python", Cmp: SiPython, color: "#3776AB" },
  sql: { label: "SQL", Cmp: Database, color: "#00D9FF" },
  django: { label: "Django", Cmp: SiDjango, color: "#0C4B33" },
  drf: { label: "Django REST Framework", Cmp: Braces, color: "#A30000" },
  fastapi: { label: "FastAPI", Cmp: SiFastapi, color: "#009688" },
  celery: { label: "Celery", Cmp: SiCelery, color: "#37814A" },
  openai: { label: "OpenAI", Cmp: RiOpenaiFill, color: "#10A37F" },
  anthropic: { label: "Anthropic Claude", Cmp: SiAnthropic, color: "#D97757" },
  langchain: { label: "LangChain", Cmp: SiLangchain, color: "#1C3C3C" },
  langgraph: { label: "LangGraph", Cmp: SiLanggraph, color: "#1C3C3C" },
  langsmith: { label: "LangSmith", Cmp: Microscope, color: "#F7A41D" },
  huggingface: { label: "Hugging Face", Cmp: SiHuggingface, color: "#FFD21E" },
  sklearn: { label: "Scikit-learn", Cmp: SiScikitlearn, color: "#F7931E" },
  postgres: { label: "PostgreSQL", Cmp: SiPostgresql, color: "#4169E1" },
  mongodb: { label: "MongoDB", Cmp: SiMongodb, color: "#47A248" },
  redis: { label: "Redis", Cmp: SiRedis, color: "#FF4438" },
  sqlite: { label: "SQLite", Cmp: SiSqlite, color: "#003B57" },
  elasticsearch: { label: "Elasticsearch", Cmp: SiElasticsearch, color: "#005571" },
  aws: { label: "AWS", Cmp: FaAws, color: "#FF9900" },
  s3: { label: "Amazon S3", Cmp: HardDrive, color: "#569A31" },
  sqs: { label: "AWS SQS", Cmp: Inbox, color: "#FF4F8B" },
  docker: { label: "Docker", Cmp: SiDocker, color: "#2496ED" },
  kubernetes: { label: "Kubernetes", Cmp: SiKubernetes, color: "#326CE5" },
  linux: { label: "Linux", Cmp: SiLinux, color: "#FCC624" },
  nginx: { label: "Nginx", Cmp: SiNginx, color: "#009639" },
  gunicorn: { label: "Gunicorn", Cmp: SiGunicorn, color: "#499848" },
  cicd: { label: "CI/CD", Cmp: InfinityIcon, color: "#22C55E" },
  githubactions: { label: "GitHub Actions", Cmp: SiGithubactions, color: "#2088FF" },
  git: { label: "Git & GitHub", Cmp: SiGit, color: "#F05032" },
  github: { label: "GitHub", Cmp: SiGithub, color: "#FFFFFF" },
  livekit: { label: "LiveKit", Cmp: SiLivekit, color: "#1FD5F9" },
  webrtc: { label: "WebRTC", Cmp: SiWebrtc, color: "#333333" },
  assemblyai: { label: "AssemblyAI", Cmp: Captions, color: "#6366F1" },
  hume: { label: "Hume AI", Cmp: HeartPulse, color: "#8B5CF6" },
  playwright: { label: "Playwright", Cmp: MousePointerClick, color: "#2EAD33" },
  selenium: { label: "Selenium", Cmp: SiSelenium, color: "#43B02A" },
  beautifulsoup: { label: "BeautifulSoup", Cmp: Soup, color: "#00D9FF" },
  scrapy: { label: "Scrapy", Cmp: SiScrapy, color: "#60A839" },
  requests: { label: "Requests", Cmp: Globe, color: "#6366F1" },
  curlcffi: { label: "curl-cffi", Cmp: SiCurl, color: "#073551" },
  rest: { label: "REST APIs", Cmp: Network, color: "#00D9FF" },
  oauth: { label: "OAuth 2.0", Cmp: KeyRound, color: "#22C55E" },
  jwt: { label: "JWT", Cmp: SiJsonwebtokens, color: "#FB015B" },
  webhook: { label: "Webhooks", Cmp: Webhook, color: "#8B5CF6" },
};

/** A technology mark. Monochrome by default; brand colour on hover of the group. */
export function TechIcon({
  slug,
  className,
  colorOnHover = true,
}: {
  slug: string;
  className?: string;
  colorOnHover?: boolean;
}) {
  const meta = techRegistry[slug];
  if (!meta) return <Circle className={className} aria-hidden />;
  const { Cmp } = meta;

  return (
    <Cmp
      className={className}
      aria-hidden
      style={colorOnHover ? ({ "--brand": meta.color } as React.CSSProperties) : undefined}
    />
  );
}

export function techLabel(slug: string) {
  return techRegistry[slug]?.label ?? slug;
}

export function techColor(slug: string) {
  return techRegistry[slug]?.color ?? "#6366F1";
}
